#SSL properties

# DataSource

spring:
  datasource:
    username: emaauth
    initialize: true
    password: MuratEmilin93
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect

# Show or not log for each sql query
    show-sql: true

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager)

# The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


#spring
  application:
    name: ema-auth-service

#server.context-path=/webservices/api/ema_auth

  profiles:
    active: prod
    
eureka:  
  client:
    serviceUrl:
      # defaultZone: http://localhost:90/eureka/
      defaultZone: http://ema-eureka-service:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true